* squeezer

  [[http://travis-ci.org/lopusz/squeezer][https://api.travis-ci.org/lopusz/squeezer.png?branch=master]]

  Seamless support for compressed files.

  [[http://clojars.org/squeezer][http://clojars.org/squeezer/latest-version.svg]]

** Usage

  Creating a compressed file is dead simple:

  #+BEGIN_SRC clojure
  (require '[squeezer.core :as sc])
  (sc/spit-compr "test.txt.gz" "test 1\ntest 2\ntest 3")
  #+END_SRC

  You can examine the file in your favourite shell to see that it works.
  #+BEGIN_SRC sh
  > file test.txt.gz
  test.txt.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)
  #+END_SRC

  You can equally easy ~slurp~ the file back:

  #+BEGIN_SRC clojure
  (require '[squeezer.core :as sc])

  (sc/slurp-compr "test.txt.gz")

  ;"test 1\ntest 2\ntest 3"
  #+END_SRC

  The desired compression algorithm is specified on the basis of the
  extension. ~.gz~ for gzip ~.bz2~ for bzip2 and ~.xz~ for xz are
  supported. You can override this behaviour by forcing compression
  using keyword ~:compr~.

  #+BEGIN_SRC clojure
  ; Do not do that!!

  (sc/spit-compr "test.txt.gz" "test 1\ntest 2\ntest 3" :compr "bzip2")
  #+END_SRC

  If you do not believe that this works, ask your favourite shell:
  #+BEGIN_SRC sh
  > file test.txt.gz
  test.txt.gz: bzip2 compressed data, block size = 900k
  #+END_SRC

  Now reading is a pain:
  #+BEGIN_SRC clojure
  (sc/slurp-compr "test.txt.gz")
  ; ZipException Not in GZIP format
  #+END_SRC

  unless you know what the trick is

  #+BEGIN_SRC clojure
  (sc/slurp-compr "test.txt.gz" :compr "bzip2")
  ; "test 1\ntest 2\ntest 3"
  #+END_SRC

  To make sure the compression algorithm is adjusted correctly, you can use the
  mime type of the file (detected, e.g., by the library [[https://github.com/michaelklishin/pantomime][pantomime]]).
** FAQ
*** How do I lazily read compressed csv file, record by record?

    It is easy.

    Add  [[https://github.com/davidsantiago/clojure-csv][clojure-csv]] and
    [[https://github.com/lopusz/squeezer][squeezer]] to your ~project.clj~.

    To read first five lines of your ~big_data.csv.gz~, type in your REPL:

    #+BEGIN_SRC clojure
    (require '[squeezer.core :as sc] '[clojure-csv :as csv])

    (->> "big_data.csv.gz"
         sc/reader-compr
         csv/parse-csv
         (take 5))
    #+END_SRC

** License

  Distributed under the Eclipse Public License, the same as Clojure.
